require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'compose/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargerRubyVersion: 2.7
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
